### ISSUE TITLE
Hopper Item Transfer Amounts

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#16]
Ability to buy "Items", "Signs" or something... to change how many items a Hopper transfers, at the moment it's set to transfer 3 items every 24 ticks so it doesn't break brewers, any faster or any more items and it breaks auto brewers , sorters , etc... what I'd like to do is give players the ability to purchase more transfer amount each time it does transfer since it doesn't effect performance at all and people won't need to place nearly as many hoppers.

**Comment by cyberpwnn** [comment]
Cannot change hopper transfer speeds in the manner you need. 
* There is no magic speed value i can just "change"
* There are no events i can "modify" or "cancel" (cancelling causes problems)

### Options
1. Instead of using hoppers, use pipes which transfer across long distances
2. Use ENDER hoppers which teleport items to the other hopper
3. Redesign the entire hopper mechanics and physics for fine control and async processing
