### ISSUE TITLE
Magnetic does not work with fortune

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#184]
Magnetic ignores the effects of of Fortune

**Comment by GetDerpy** [comment]
Magnetic also does not work on spawners, and if you break a block which is say 2/3 high such as sugarcane or cactus, only the one you hit goes into your inventory, the rest drop.

**Comment by cyberpwnn** [comment]
### Magnetic also does not work on spawners
This is because of the complex nature in events/spawner breaking. It will remain that way along with the purpose of people not accidentally breaking spawners

### Sugarcane and Cactus dropping
This is minecraft doing that. I cannot control the dropping, the only thing i can do is search for them, but that is more time on the cpu i dont want to scan for. also, is this out of the 3x3x3 radius?

**Comment by cyberpwnn** [comment]
There is no way to handle fortune unless i manually just start hacking in more drops which doesnt really seem good to do.

**Comment by cyberpwnn** [comment]
Continuing with a hacky fortune implementation.

**Comment by cyberpwnn** [comment]
also an issue with blast

**Comment by cyberpwnn** [comment]
TITLE THINGS

**Comment by cyberpwnn** [comment]
Im not strapping nms code into effex https://bukkit.org/threads/get-drops-on-blockbreakevent-with-fortune.271408/
