### ISSUE TITLE
Noticable Ping issue on all servers (besides factions)

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#196]
When I usually get 60 ping, I am currently getting 150 to 300 ping on all servers. I have tried a different network, and same results happen. Half of the people on right now have 4 to 3 bars on tab menu, indicating they have 100 ping or higher. Takes approximately 10 seconds to join each server with both the Compass, and with /server. This could be my ping because other servers indicate I have the same range of ping, but I asked, and a lot of people are noticing a big ping drop.

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/19405290/e9a7f8e4-9243-11e6-9504-b60da5c39085.png)

Here is the link speed from the lobby. The link speed is about 50ms on average. so if you are getting a normal ping of 60, the extra 50ms would make it roughly 100ms

However if you are on factions, you may get a link speed ranging from 100 (60+50) or even higher due to the different nodes on the network.

Everything you do in game has to go through the bungeecord network, then to the server, then back through the bungeecord network, and back to you. This is the bulk you are experiencing.

Ill see if @SwiftSwamp can tweak some of the connections to get them a bit faster, because ping is really important.

**Comment by SwiftSwamp** [comment]
Hubs, Factions and Skyblock are on the same node as Bungee.. however turns out this was user end only, no one else was experiencing the same problem. According to react, my ping was even as low as 22ms on some servers.
