### ISSUE TITLE
Spawner Levelling not being able to use in some spawners

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#197]
Spawners placed before the spawner leveling was introduced are not able to be upgraded, however, it still costs 25% of the spawner price to mine and replace them in order to use the leveling.

**Comment by cyberpwnn** [comment]
Spawners placed before the spawner leveling was introduced are not able to be upgraded

This isnt exactly true, all spawners placed in since the update have been recorded in nest. If there are any problematic ones, show me some. Keep in mind that world edit and or copying blocks will not work. The blocks are nested when you place them. Copying does not work.

### Issue split into multiple
* Levelling up spawners should add to the f top value. #198
* There should also be a warmup for the spawner mining cost. #199
* When punching, or beginning to mine a spawner, it should alert you to the cost. #200

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/80486850488f7546d25363df7fb906c16da30a76
