### ISSUE TITLE
Denying Teleportation into a Region

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#310]
There's a similar bug much like what happened with the Ender Pearl Usage where sometimes when you're randomly running around and if you jump off / onto a half slab, it'll send the message "You cannot teleport into that Region! KOTH" and you'll get stuck with that message getting spammed.

**Comment by GetDerpy** [comment]
I think this is to do with NCP being overly sensitive about movements. When you move onto a slab in some scenarios, NCP will think you made an illegal move and try to teleport you back, but because teleportation is disabled in KOTH zones (Can't even /tpo into koth), you are spammed with this message as NCP continuously tries to teleport you back. NCP trying to teleport you, and the plugin blocking the teleport, results in you being stuck on the slab. Blocking your sword seems to fix this.

**Comment by SwiftSwamp** [comment]
So this is only happening in KOTH Regions? I was under the impression it was happening anywhere.

**Comment by GetDerpy** [comment]
You get glitched in slabs anywhere, the only time you get spammed with cannot tp is in enemy land and koth.

**Comment by cyberpwnn** [comment]
So, what are we going to do about it?

**Comment by SwiftSwamp** [comment]
I've since changed / updated the way the Anti Cheat system handles everything, should no longer be an issue.
