### ISSUE TITLE
Some prison plots have been overclaimed.

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#474]
Including spawn.
![image](https://cloud.githubusercontent.com/assets/22468195/20252663/fe5a0982-aa88-11e6-988e-fcdf201d26a1.png)

**Comment by CosmicFyre** [comment]
Update: someone overclaimed someones plot that had all their stuff stored on it.

**Comment by SwiftSwamp** [comment]
At the start the Database wasn't connecting so I'm not sure how anyone was even being allowed to claim a plot, however if you only had a single plot you should still own it, if you had multiple merge, may be an issue.. but just contact an Admin to help get your plot back, regarding lost items, sorry about that .-. But it's been fixed since 12 hours after day 1.
