### ISSUE TITLE
Staff Chat

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#572]
Let's put that new Transmission to use, there should be an in-game staff chat where staff can speak globally / freely where only other staff will receive / see the messages, either that or you could hook into DeluxeChat.

**Comment by cyberpwnn** [comment]
No. Use transmission for that, not PPAs

PPA's are used for transferring IMPORTANT data not quickly but RELIABLY. 

Use bungeecord for that. You can't send a message to a server with no players on it, but it wouldn't matter because no one is on that server, so there is no reason to even try to send it anyways lol. Also, Transmission is blazing fast. PPAs are gawd awful slow.
