### ISSUE TITLE
/Fix all bug in factions

### ISSUE THREAD

**Issue by Assurinq** [cyberpwnn/GlacialRealms#612]
When you do /fix all it will say that you're in combat even when you aren't then the cooldown comes and you get the cooldown even when you didn't fix anything

**Comment by cyberpwnn** [comment]
@SwiftSwamp  Commune combat cool down separate from the tagger

**Comment by SwiftSwamp** [comment]
I don't understand what I was tagged for, this isn't something I can fix?

**Comment by cyberpwnn** [comment]
Check the cooldown for fix

**Comment by SwiftSwamp** [comment]
You cannot do the command while in combat and the cooldown timer still get's set off even if it can't be used.

- I'm in combat.
- Fix has a 10m cooldown
- I try to use it during combat but I can't since I'm in combat
- I get out of combat, I still can't use fix because I have to wait until the timer resets even though I couldn't use it during combat.
