### ISSUE TITLE
MCMMO Treefeller ability

### ISSUE THREAD

**Issue by CosmicFyre** [cyberpwnn/GlacialRealms#676]
The treefeller ability doesn't work, it also wont give you woodcutting xp while active

**Comment by SwiftSwamp** [comment]
I believe skills is overriding this, needs confirmation.

**Comment by cyberpwnn** [comment]
MCMMO is supposed to not exist

**Comment by cyberpwnn** [comment]
Also, the entire reason we agreed mcmmo should be removed when icing is being used is because **icing does not conflict with mcmmo at all** meaning players would be able to stack unarmed in both plugins and break the game (as i i have seen a few people do, then others report that icing unarmed is too op) when really damage is being multiplied to incredible numbers.

If mcmmo isnt working and you want to blame it on icing, then test it lol **disable icing**. If mcmmo starts to work, report it here.

**Comment by SwiftSwamp** [comment]
Comment is 14 days old, already confirmed that Skills does in no way interfere with McMMO, also we spoke about this in a Skype call, McMMO was reenabled because Icing lacks a lot of features that people frequently used in McMMO, that's why it was added back. You were away so I figured I'd readd it for the time being while other bugs are fixed before more content is added.
