### ISSUE TITLE
McMMO Axes not working

### ISSUE THREAD

**Issue by CondensateTribe** [cyberpwnn/GlacialRealms#678]
When attacking mobs with axes to get your axes level up for McMMO, the level won't go up at all. I was killing blazes while doing this testing.

**Comment by SwiftSwamp** [comment]
I believe /skills is overriding this, needs confirmation.

**Comment by CondensateTribe** [comment]
We found out the problem. You needed to be hit by the mobs in order for the mcmmo to kick in. Although, McMMO skills like Skull Splitter, and unarmed are disabled on Skyblock. Is that supposed to happen.

**Comment by SwiftSwamp** [comment]
"You need to be hit by mobs in order for it to work", well that's how it's always been, I've never changed anything since Day 1 and it hasn't been updated as they quit updating the 1.8 version.
All PvP related McMMO Skills / Abilities have been disabled since day 1 as well, they were deemed to op even when extremely nerfed.

**Comment by cyberpwnn** [comment]
MCMMO Is planned to be removed isnt that correct?

**Comment by SwiftSwamp** [comment]
Everyone was complaining about it not being gone, there's still to much content provided by it that we do not provide yet.

**Comment by SwiftSwamp** [comment]
We're turning the Mob AI back on anyways, caused because mobs aren't fighting back and need to hit you at least once.
