### ISSUE TITLE
Lower unarmed or remove it

### ISSUE THREAD

**Issue by dragonking1121** [cyberpwnn/GlacialRealms#700]
Unarmed at way to op since only few person have it to 1000 u can literally unarmed Somone in few hit I think it should be removed or lower to 200

**Comment by cyberpwnn** [comment]
What about a diamond sword?

Isnt armor common? Because diamond swords can 2-3 hit someone while unarmed can 3-4 hit someone WITHOUT ARMOR, however with leather armor, you can survive an extra hit, iron making it feel like a stone or even wooden sword.

Also, a fist can be very punishing to the cranium. 

Ill leave this to open discussion i guess.

**Comment by SwiftSwamp** [comment]
Tweaks have been made accordingly, he's more or less referring to McMMO.
