### ISSUE TITLE
Able to drop enchant any enchant on any piece of armor

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#711]
You are able to drop enchant any enchant on any piece of armor / weapon / tool regardless what it's only meant for, however doing so renders it useless. i.e. Say I drop enchanted Magnetic onto my Diamond Sword, it'll let me drop enchant it on the sword but the enchant won't take affect.

**Comment by cyberpwnn** [comment]
Because magnetic isn't intended for the use of diamond swords. The only thing that would work with mag on a diamond sword is digging cobweb. That would require an entire restructure of enchantments (we would HAVE to go elemental to make enchantments crossable like that)

If you want something elemental like that, make an issue for the additions (restructure of enchantments)

**Comment by SwiftSwamp** [comment]
I don't think you understood the issue, you already can drop enchant any enchantment on any piece of armor or weapon despite what it's meant for.

Example, Blast is say only meant for TNT And Pickaxes, however I can put it on chestplates, axes, swords, etc... and of course it won't work (It's not meant to work, the bug is that you can put it on anything despite what it's only allowed for)

**Comment by cyberpwnn** [comment]
YOU ASKED FOR THAT 
https://github.com/cyberpwnn/Effex/commit/79cf300a03da286ffb451d94c1c604c27b1f9bc0

![image](https://cloud.githubusercontent.com/assets/10619135/21597686/a8d7f4be-d11c-11e6-9186-67808501a2aa.png)
