### ISSUE TITLE
Power Bomb doesn't count towards /blocks

### ISSUE THREAD

**Issue by WolfiezRawr** [cyberpwnn/GlacialRealms#724]
Proof: [https://www.youtube.com/watch?v=1HxwCdfqba8](url)

**Comment by cyberpwnn** [comment]
This is because whatever plugin handles that functionality isnt hooking into the event system (and with good reason too)

For example if you use the blast enchantment, it wont count all 9 of them, it will only count the block you actually broke. 

There isnt really a way to fix it without hacking around which usually causes major instabilities in plugins,.
